#ifndef KEYDEFS_H
#define KEYDEFS_H

#include "wiiu.h"

#define KEY_LEFT    (VPAD_BUTTON_LEFT|VPAD_STICK_L_EMULATION_LEFT|VPAD_STICK_R_EMULATION_LEFT)
#define KEY_RIGHT   (VPAD_BUTTON_RIGHT|VPAD_STICK_L_EMULATION_RIGHT|VPAD_STICK_R_EMULATION_RIGHT)
#define KEY_UP      (VPAD_BUTTON_UP|VPAD_STICK_L_EMULATION_UP|VPAD_STICK_R_EMULATION_UP)
#define KEY_DOWN    (VPAD_BUTTON_DOWN|VPAD_STICK_L_EMULATION_DOWN|VPAD_STICK_R_EMULATION_DOWN)
#define KEY_CANCEL  (VPAD_BUTTON_B)
#define KEY_CONFIRM (VPAD_BUTTON_A|VPAD_BUTTON_PLUS)
#define KEY_X       (VPAD_BUTTON_X)
#define KEY_EXTRA   (VPAD_BUTTON_ZL|VPAD_BUTTON_ZR)
#define KEY_DELETE  (VPAD_BUTTON_X)

#endif // KEYDEFS_H