#ifndef KEYDEFS_H
#define KEYDEFS_H

#include <allegro5/allegro.h>

#define KEY_LEFT    (ALLEGRO_KEY_LEFT)
#define KEY_RIGHT   (ALLEGRO_KEY_RIGHT)
#define KEY_UP      (ALLEGRO_KEY_UP)
#define KEY_DOWN    (ALLEGRO_KEY_DOWN)
#define KEY_CANCEL  (ALLEGRO_KEY_ESCAPE)
#define KEY_CONFIRM (ALLEGRO_KEY_ENTER)
#define KEY_EXTRA   (ALLEGRO_KEY_LCTRL)
#define KEY_DELETE  (ALLEGRO_KEY_DELETE)
#define KEY_UNDO    (ALLEGRO_KEY_Z)
#define KEY_REDO    (ALLEGRO_KEY_Y)
#define KEY_OPEN    (ALLEGRO_KEY_O)
#define KEY_SAVE    (ALLEGRO_KEY_S)
#define KEY_GRID    (ALLEGRO_KEY_G)

#endif // KEYDEFS_H